json_dir : '/data/zhangyichi/Trustworthy-MLLM/data/fairness/preference.json'
image_dir: '/data/zhangyichi/Trustworthy-MLLM/data/fairness/stereo_query_images'
unrelated_image_dir: '/data/zhangyichi/Trustworthy-MLLM/data/unrelated_images'