dataset_id: "d-advanced-spatial"
model_id: "llava-v1.5-7b"

log_file: "./logs/truthfulness/d-advanced-spatial.json"

evaluator_seq_cfgs:
  [
    {
      "rule_yes_or_no_eval":
        {  
          metrics_cfg: { pred_mean: {} }
        }
    }
  ]
