model:
  model_name: 'llava-v1.5-13b'
  model_path: '/data/zhangyichi/Trustworthy-MLLM/playground/model_weights/llava-v1.5-13b'

parameters:
  sep: ','
  temperature: 0
  top_p: None
  num_beams: 1
  max_new_tokens: 512