model:
  model_name: 'llava-rlhf-13b'
  model_path: './playground/model_weights/llava-rlhf-13b/sft_model'
  lora_path: "./playground/model_weights/llava-rlhf-13b/rlhf_lora_adapter_model"
parameters:
  sep: ','
  temperature: 0
  top_p: None
  num_beams: 1
  max_new_tokens: 512