model:
  model_name: 'llava-v1.5-7b'
  model_path: './playground/model_weights/LVIS-Instruct4V-Nodetail-mix619k-7b'

parameters:
  sep: ','
  temperature: 0
  top_p: None
  num_beams: 1
  max_new_tokens: 512