dataset_id: "profession-pred-with-description"
model_id: "llava-v1.5-7b"
log_file: "./logs/fairness/profession-pred-with-description.json"
generation_kwargs: {
    'max_new_tokens': 100,
    'do_sample': False,
}

dataset_cfg: 
  prompt_w_description: True

evaluator_seq_cfgs:
  [
    {
      "rule_reject_template_eval":
        { metrics_cfg: { pred_no_op: {}, pred_mean: {} } },
    },
  ]
