clean_image_dir: '/data/zhangyichi/Trustworthy-MLLM/data/robustness/at_nips/source/clean'
untarget_image_dir: '/data/zhangyichi/Trustworthy-MLLM/data/robustness/at_nips/source/untarget'
annotation_file: '/data/zhangyichi/Trustworthy-MLLM/data/robustness/at_nips/label/ann.json'
