clean_image_dir: '/data/zhangyichi/Trustworthy-MLLM/data/robustness/adv_nips/source/clean'
target_image_dir: '/data/zhangyichi/Trustworthy-MLLM/data/robustness/adv_nips/source/target'
annotation_file: '/data/zhangyichi/Trustworthy-MLLM/data/robustness/adv_nips/label.json'
