clean_image_dir: '/data/zhangyichi/Trustworthy-MLLM/data/robustness/at_nips/source/clean'
target_image_dir: '/data/zhangyichi/Trustworthy-MLLM/data/robustness/at_nips/source/target'
annotation_file: '/data/zhangyichi/Trustworthy-MLLM/data/robustness/at_nips/label/ann.json'
