related_image_dir: '/data/zhangyichi/Trustworthy-MLLM/data/robustness/advglue_plus/related'
unrelated_image_dir: '/data/zhangyichi/Trustworthy-MLLM/data/unrelated_images'
annotation_file: '/data/zhangyichi/Trustworthy-MLLM/data/robustness/advglue_plus/label.json'
