clean_image_dir: '/data/zhangyichi/Trustworthy-MLLM/data/robustness/adv_nips/source/clean'
untarget_image_dir: '/data/zhangyichi/Trustworthy-MLLM/data/robustness/adv_nips/source/untarget'
annotation_file: '/data/zhangyichi/Trustworthy-MLLM/data/robustness/adv_nips/label.json'
