related_image_dir: '/data/zhangyichi/Trustworthy-MLLM/data/robustness/dt/related'
unrelated_image_dir: '/data/zhangyichi/Trustworthy-MLLM/data/unrelated_images'
annotation_file: '/data/zhangyichi/Trustworthy-MLLM/data/robustness/dt/style_sample100.json'
