DATA_ROOT: "/data/zhangyichi/Trustworthy-MLLM/data/fairness"
image_dir: '/data/zhangyichi/Trustworthy-MLLM/data/fairness/stereo_query_images/related_images'
questions_dir: '/data/zhangyichi/Trustworthy-MLLM/data/fairness/stereo_query.csv'