DATA_ROOT: "/data/zhangyichi/Trustworthy-MLLM/data/fairness"
image_dir: '/data/zhangyichi/Trustworthy-MLLM/data/fairness/stereo_classification_images'
statement_dir: '/data/zhangyichi/Trustworthy-MLLM/data/fairness/stereo_classification.csv'