annotation_file: /data/zhangyichi/Trustworthy-MLLM/data/privacy/data/vizwiz-priv/Annotations/Vizwiz-Priv-Recognition.json
image_dir: /data/zhangyichi/Trustworthy-MLLM/data/privacy/data/vizwiz-priv/Filling_Images
