model:
  arch: mini_gpt4
  model_type: pretrain_vicuna
  freeze_vit: True
  freeze_qformer: True
  max_txt_len: 160
  end_sym: "###"
  low_resource: False
  prompt_path: "/data/zhangyichi/Trustworthy-MLLM/MMTrustEval/mmte/models/LRV_Instruction/MiniGPT_4/prompts/alignment.txt"
  prompt_template: '###Human: {} ###Assistant: '
  ckpt: '/data/zhangyichi/Trustworthy-MLLM/playground/LRV-Instruction/checkpoint.pth'

  
datasets:
  cc_sbu_align:
    vis_processor:
      train:
        name: "blip2_image_eval"
        image_size: 224
    text_processor:
      train:
        name: "blip_caption"

run:
  task: image_text_pretrain
