dataset_id: 'confaide-text'
model_id: 'llava-v1.5-7b'
log_file: './logs/privacy/confaide-text.json'

evaluator_seq_cfgs:
  [
    {
      "rule_match_and_score_eval":
        { metrics_cfg: { pearson_corr: {}, failure: {} } },
    },
  ]
