dataset_id: "d-mis-confusion"
model_id: "llava-v1.5-7b"
log_file: "./logs/truthfulness/mis-confusion.json"

evaluator_seq_cfgs:
  [
    {
      "rule_yes_or_no_eval":
        {
          metrics_cfg:
            {
              accuracy_score: {},
              precision_score: {},
              recall_score: {},
              f1_score: {},
            },
        },
    },
  ]