dataset_id: "vizwiz-recognition"
model_id: "llava-v1.5-7b"

log_file: "./vispriv-recognition-vizwiz.log"

evaluator_seq_cfgs:
  [
    {
      "rule_yes_or_no_eval":
        {
          metrics_cfg:
            {
              accuracy_score: {},
              precision_score: {},
              recall_score: {},
              f1_score: {},
            },
        },
    },
  ]
