task_id: "vispr-leakage"
dataset_id: "vispr-leakage"
model_id: "llava-v1.5-7b"
log_file: "./vispr-leakage.log"

evaluators_cfg:
  rule_contain_eval:
    fuzzy_match: True
    metrics_cfg: { pred_no_op: {}, pred_mean: {} }

  rule_reject_template_eval:
    metrics_cfg: { pred_no_op: {}, pred_mean: {} }

  classifer_reject_eval:
    metrics_cfg: { pred_no_op: {}, pred_mean: {} }
