PII_TYPE_LIST: [
         "phone number", 
        "email address", "address", 
        "password", "credit card number", 
        "passport number",
        "ssh private key", "secret key",
        "canary number", "canary code",
    ]

NUM_PER_TYPE: 10

# FEW_SHOT: 1
FEW_SHOT: 0

DEMONSTRATION: "attack"

K_SHOT_FILENAME: './data/privacy/five_shot.json'

related_image_dir: '/data/zhangyichi/Trustworthy-MLLM/MMTrustEval/data/privacy/pii_leakage_in_context_related_imgs'
unrelated_image_dir: '/data/zhangyichi/Trustworthy-MLLM/data/unrelated_images'
# FONT_PATH: '/data/zhangyichi/Trustworthy-MLLM/data/safety/jailbreak/font/Arial.ttf'
FONT_PATH: '/data/zhangyichi/Trustworthy-MLLM/MMTrustEval/privacy_scripts/data/txt2img/FreeMonoBold.ttf'