model: 
  llama_dir: '/data/zhangyichi/Trustworthy-MLLM/playground/model_weights/LLaMA-7B'
  model_path: '/data/zhangyichi/Trustworthy-MLLM/playground/model_weights/LLaMA-Adapter-V2/7fa55208379faf2dd862565284101b0e4a2a72114d6490a95e432cf9d9b6c813_BIAS-7B.pth'
  # llama_model: "meta-llama/Llama-2-7b-chat-hf"

parameters:
  max_gen_len: 256
  temperature: 0.1
  top_p: 0.75